on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build All
      if: matrix.os == 'ubuntu-latest'
      run: dotnet build --configuration Release
    - name: Build Library
      run: dotnet build src --configuration Release