on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"
env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: |
        dotnet pack src \
          -p:PackageVersion="${VERSION}" \
          --configuration Release \
          --verbosity normal \
          --output .
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: nupkg
        path: |
          *.nupkg

  deploy-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Push to GitHub
        run: |
          ls -al
          ls nupkg/
          dotnet nuget push nupkg/*.nupkg \
            --source ${FEED_URL} \
            --api-key ${FEED_KEY} \
            --no-symbols true \
            --skip-duplicate \
            --diagnostics
        env:
          FEED_URL: https://nuget.pkg.github.com/wcoder/index.json \
          FEED_KEY: ${{ secrets.GITHUB_TOKEN }}