on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+-preview[0-9]+"
env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - name: Pack
      run: |
        dotnet pack FB2Library/FB2Library.csproj \
          -p:NuspecFile=../nuget/FB2Library.nuspec \
          -p:NuspecProperties="version=${VERSION}" \
          --configuration Release \
          --verbosity normal \
          --include-symbols \
          --include-source \
          --output .
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: '*.nupkg'

  deploy-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: nupkg
      - name: Push to GitHub
        run: |
          dotnet nuget push ./nupkg/FB2Library.*.nupkg \
            --source ${FEED_URL} \
            --api-key ${FEED_KEY}
        env:
          FEED_URL: https://nuget.pkg.github.com/wcoder/index.json \
          FEED_KEY: ${{ secrets.GITHUB_TOKEN }}